version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: github.com/sirupsen/logrus
    versions:
    - 1.7.0
  - dependency-name: github.com/stretchr/testify
    versions:
    - 1.6.1
- package-ecosystem: npm
  directory: "/web"
  schedule:
    interval: monthly
    time: "20:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.2.2
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
  - dependency-name: "@types/react"
    versions:
    - 17.0.0
    - 17.0.2
  - dependency-name: "@types/matter-js"
    versions:
    - 0.14.10
    - 0.14.8
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
  - dependency-name: "@material-ui/core"
    versions:
    - 4.11.2
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: lodash
    versions:
    - 4.17.19
  - dependency-name: handlebars
    versions:
    - 4.7.6
