language: go

env:
  - GO111MODULE=on POSTGRES_USER=postgres POSTGRES_DB=db DB_HOST=localhost

services:
  - postgresql

install:
  - go mod download
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/pressly/goose/cmd/goose

before_script:
  - psql -c 'create database db;' -U postgres
  - make goose/up

script:
  - go test -v ./... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
