language: go

env:
  - GO111MODULE=on POSTGRES_USER=postgres POSTGRES_DB=db DB_HOST=localhost

cache:
  directories:
    - $GOPATH/pkg/mod
    - web/node_modules

services:
  - postgresql

install:
  - go mod download
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls
  - go get github.com/pressly/goose/cmd/goose

before_script:
  - psql -c 'create database db;' -U postgres
  - make goose/up
  - make rsa
  - export JWT_RSA_PRI=`base64 jwt.rsa`
  - export JWT_RSA_PUB=`base64 jwt.rsa.pub`

script:
  - go test -v ./ ./internal/... -covermode=count -coverprofile=coverage.out
  - $HOME/gopath/bin/goveralls -coverprofile=coverage.out -service=travis-ci
  - cd web
  - yarn install
  - yarn lint
  - yarn test
